# TrajClient params
X_des: [8.000000,0.300000,0.000000,0.000000,0.000000,0.000000]
timestep: 0.02

# Rampup params
kp_ramp: 0.45
kd_ramp: 0.05
ki_ramp: 0.1
accel_ramp: 3
target_vel_ramp: 3
timeout_ramp: 2.5

# iLQR params
timeout_ilqr_mpc: 5
stop_goal_threshold: 0.3

ilqr_tolFun: 0.0000001
ilqr_tolConstraint: 0.0000001
ilqr_tolGrad: 0.00001
ilqr_max_iter: 20
ilqr_regType: 1
ilqr_debug_level: 2

Opt_car_param: {g: 9.81, m: 2.35, L: 0.257, b: 0.14328,
                c_x: 116, c_a: 197, Iz: 0.025, mu: 1.31, mu_s: 0.55,
                limThr: [0, 4.0], limSteer: [-0.68, 0.76]}
Opt_cost: {cu: [0.01, 0.01], cdu: [1.0, 1.5],
           cf: [10, 10, 5, 10, 0.1, 0.1],
           pf: [0.01, 0.01, 0.1, 0.1, 0.1, 0.1],
           cx: [0.05, 0.05, 0.04], cdx: [0.001, 0.005, 0.002],
           px: [0.01, 0.01, 0.1],
           cdrift: -0.001,
           k_pos: 0.5, k_vel: 0, d_thres: 0.3}

######
# TrajServer params
old_msg_discard_thres: 0.5

# Obstacle detection params
scan_clip_angle: 0.35 #radians
naive_obstacle_dist_thres: 1.5
naive_obstacle_percent_thres: 0.2
